### PR TITLE
Upgrade to Mongo 4.0

### PR DESCRIPTION
**Pull request by mrtmm**
For the Lilac release, Mongo was upgraded from 3.6. to 4.0.

Update our playbooks for the same.

### CODE REVIEW

**Comment by elenalind** [comment]
Maari, please note that I don't think I have permission to approve PRs in this repo.

**Comment by mrtmm** [comment]
Yes, I figured, if you don't have any objections I'll go ahead and merge :)

**Comment by elenalind** [comment]
Please do, no objections! :)

**Comment by elenalind** [comment]
Just noticed that there a mongo_3_6.yml playbook, so we might want to rename it and/or update it as well. 

ubuntu@ubuntu-qa-deploy-fra1:~/edx-configuration$ grep -iR mongo_3_6 *
playbooks/edx_continuous_integration.yml:    - mongo_3_6
grep: warning: playbooks/edx-east: recursive directory loop
playbooks/hastexo-single-node.yml:    - mongo_3_6
playbooks/mongo_3_6.yml:# as used by mongo_replica_set in the mongo_3_6 role.
playbooks/mongo_3_6.yml:# ansible-playbook mongo_3_6.yml -i 203.0.113.11,203.0.113.12,203.0.113.13 -e@/path/to/edx.yml -e@/path/to/ed.yml
playbooks/mongo_3_6.yml:# ansible-playbook mongo_3_6.yml -i any-cluster-ip -e@/path/to/edx.yml -e@/path/to/ed.yml --tags configure_replica_set
playbooks/mongo_3_6.yml:# ansible-playbook mongo_3_6.yml -i 203.0.113.11,203.0.113.12,new-machine-ip -e@/path/to/edx.yml -e@/path/to/ed.yml
playbooks/mongo_3_6.yml:    - mongo_3_6
playbooks/hastexo-multi-node.yml:    - mongo_3_6
playbooks/openedx_native.yml:    - role: mongo_3_6

**Comment by mrtmm** [comment]
There are quite a few old ones around still under `/playbooks`. I think that is a general maintenance issue for the repo and we don't have to worry about that at this point. We can just make the switch to run with the latest.

**Pull request merged**
