### PR TITLE
Include OpenStack playbook run instructions

### PR DESCRIPTION
**Pull request by arbrandes**
@fghaas, should we squash all these commits, to make it easier to create an upstream  PR later?

### CODE REVIEW

**Comment by fghaas** [comment]
@arbrandes Yes, squashing them is exactly what I suggested by email. However, it would be great if you could split b637801 into two commits:

1. one that only modifies the README;
2. one that modifies the Ansible bits.

Then ideally you would squash (1) with all my commits, and insert (2) **before** (1) in the commit history.

Can you take care of that?

**Comment by arbrandes** [comment]
Sure, working on it!

**Comment by arbrandes** [comment]
PR updated!

**Comment by fghaas** [comment]
And merged, thanks @arbrandes and @deenac!

**Pull request merged**
